---
name: Release

on:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  GO_VERSION: 1.17
  GORELEASER_VERSION: v0.146.0

jobs:
  create-packages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Setup Mage
        run: |
          git clone https://github.com/magefile/mage
          cd mage
          go run bootstrap.go

      - name: Setup GoReleaser
        run: |
          curl -O -L https://github.com/goreleaser/goreleaser/releases/download/${{ env.GORELEASER_VERSION }}/goreleaser_amd64.deb
          sudo dpkg -i goreleaser_amd64.deb
          rm goreleaser_amd64.deb

      - name: Set GoReleaser flags
        id: set-goreleaser-flags
        run: |
          if ${{ startsWith(github.ref, 'refs/tags') }} ; then
            echo "::set-output name=GORELEASER_FLAGS::--rm-dist --skip-validate"
          else
            echo "::set-output name=GORELEASER_FLAGS::--rm-dist --snapshot --skip-publish --skip-validate"
          fi

      - name: Build packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goreleaser release ${{ steps.set-goreleaser-flags.outputs.GORELEASER_FLAGS }}

      - name: Upload packages artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: dist

  publish-s3:
    needs: create-packages
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@master

      - name: Install packages required for publishing script
        run: |
          sudo apt-get -y update
          sudo apt-get install -y procmail awscli reprepro

      - name: Build createrepo_c tool
        run: |
          git clone https://github.com/rpm-software-management/createrepo_c.git && cd createrepo_c/
          git checkout 0.17.1
          mkdir build && cd build
          sudo apt install -y libbz2-dev cmake libmagic-dev \
            libglib2.0-dev libcurl4-openssl-dev libxml2-dev \
            libpython3-dev librpm-dev libssl-dev libsqlite3-dev \
            liblzma-dev zlib1g-dev libzstd-dev doxygen
          cmake .. -DWITH_ZCHUNK=OFF -DWITH_LIBMODULEMD=OFF
          make -j $(nproc)
          sudo make install
          cd ../..

      - name: Import GPG key
        run: |
          mkdir -p ~/.gnupg
          echo 'digest-algo sha256' >> ~/.gnupg/gpg.conf
          gpg --import <(echo "${{ secrets.GPG_KEY }}")

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Setup Mage
        run: |
          git clone https://github.com/magefile/mage
          cd mage
          go run bootstrap.go

      - name: Download packages artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: dist

      - name: Publish packages to S3 repo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GPG_SIGN_KEY: ${{ secrets.GPG_SIGN_KEY }}
          S3_UPDATE_REPO_SCRIPT_URL: ${{ secrets.S3_UPDATE_REPO_SCRIPT_URL }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_FOLDER: release/modules
        run: mage publishS3
