---
name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  GO_VERSION: 1.15
  GORELEASER_VERSION: v0.146.0

jobs:
  create-packages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Setup Mage
        run: |
          git clone https://github.com/magefile/mage
          cd mage
          go run bootstrap.go

      - name: Setup GoReleaser
        run: |
          curl -O -L https://github.com/goreleaser/goreleaser/releases/download/${{ env.GORELEASER_VERSION }}/goreleaser_amd64.deb
          sudo dpkg -i goreleaser_amd64.deb
          rm goreleaser_amd64.deb

      - name: Set GoReleaser flags
        id: set-goreleaser-flags
        run: |
          if ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }} ; then
            echo "::set-output name=GORELEASER_FLAGS::--rm-dist --skip-validate"
          else
            echo "::set-output name=GORELEASER_FLAGS::--rm-dist --snapshot --skip-publish --skip-validate"
          fi

      - name: Build packages
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: |
          goreleaser release ${{ steps.set-goreleaser-flags.outputs.GORELEASER_FLAGS }}

      - name: Upload packages artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: dist

  publish-s3:
    needs: create-packages
    runs-on: ubuntu-18.04
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@master

      - name: Install packages required for publishing script
        run: |
          sudo apt-get -y update
          sudo apt-get install -y procmail createrepo awscli reprepro

      - name: Import GPG key
        run: |
          mkdir -p ~/.gnupg
          echo 'digest-algo sha256' >> ~/.gnupg/gpg.conf
          gpg --import <(echo "${{ secrets.GPG_KEY }}")

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Setup Mage
        run: |
          git clone https://github.com/magefile/mage
          cd mage
          go run bootstrap.go

      - name: Download packages artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: dist

      - name: Set S3_FOLDER
        id: set-s3-folder
        run: |
          if ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }} ; then
            echo "::set-output name=S3_FOLDER::release/modules"
          else
            echo "::set-output name=S3_FOLDER::check/modules"
          fi

      - name: Publish packages to S3 repo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GPG_SIGN_KEY: ${{ secrets.GPG_SIGN_KEY }}
          S3_UPDATE_REPO_SCRIPT_URL: ${{ secrets.S3_UPDATE_REPO_SCRIPT_URL }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_FOLDER: ${{ steps.set-s3-folder.outputs.S3_FOLDER }}
        run: mage publishS3

  update-brew-formula:
    name: Bump Homebrew formula
    runs-on: macos-latest
    steps:
      - name: Homebrew bump formula
        uses: dawidd6/action-homebrew-bump-formula@v3.7.1
        with:
          formula: cartridge-cli
          token: ${{ secrets.BUMP_HOMEBREW_FORMULA_TOKEN }}
