name: Update translation sources

on:
  push:
    paths:
      - '*.rst'
      - 'rst/**.po'
    branches:
      - master
jobs:
  autocommit-pot-files:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2

    - name: Setup Python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r doc/requirements.txt

    - name: Build pot files
      run: python -m sphinx . doc/locale/en -c doc -b gettext

    - name: Push Pot-files to crowdin
      uses: crowdin/github-action@1.1.0
      with:
        config: 'doc/crowdin.yaml'
        upload_sources: true
        upload_translations: true
        import_eq_suggestions: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        CROWDIN_PERSONAL_TOKEN: ${{secrets.CROWDIN_PERSONAL_TOKEN}}
